### ISSUE TITLE
controller-selector doesn't work with glibc earlier than 2.38

### ISSUE THREAD

**Issue by rea987** [Tau5/Co-op-on-Linux#2]
controller-selector doesn't work with glibc 2.35 on Ubuntu Mate 22.04.4 LTS.

https://gist.github.com/rea987/b9c64a057589e97dc4fcd9ddbe1b75e7

Used release; v0.3.

**Comment by Tau5** [comment]
[controller-selector.zip](https://github.com/user-attachments/files/16300837/controller-selector.zip)
Can you replace the appimage in controller-selector with the one in the zip and test if it works? You can also just open the appimage and test if it opens

**Comment by rea987** [comment]
v0.4.0 release of the tool has the controller-selector launched on Ubuntu Mate 22.04 using glibc 2.35.
