### ISSUE TITLE
./create-new-profile.sh: 21: Syntax error: "(" unexpected (expecting "done")

### ISSUE THREAD

**Issue by ristiisa** [Tau5/Co-op-on-Linux#8]
Happens right after selecting the executable to run

```
./create-new-profile.sh: 21: Syntax error: "(" unexpected (expecting "done")
```

**Comment by Tau5** [comment]
Do you have `zenity` installed?

**Comment by ristiisa** [comment]
yes

**Comment by ristiisa** [comment]
it seems if I remove outermost () around assigments on lines 21, 23, 24 the script continues

**Comment by ThomasLewis1028** [comment]
I also noticed the issue and have `zenity` installed. Removing the same lines that @ristiisa mentioned, it does seem to fix it. I opened a pull request #9 that fixes this issue.
